/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "tds-i32d"
// include("lesson01-calendar")
// include("lesson03-stack-tests")
include("lesson04-immutability")
include("lesson05-calendar")
include("lesson06-prefix-calculator")